version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: autivo_test
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    restart: unless-stopped

